name: CI
on:
  push:
  pull_request:
      types:
        - opened
  workflow_dispatch: # Allow manual execution of the workflow
concurrency: ${{ github.workflow }}-${{ github.ref }}
permissions:
  contents: read # Added for better security
jobs:
  Lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4.1.0
      - uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: pnpm
      - run: pnpm install
      - run: pnpm lint

  Types:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4.1.0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install
      - run: pnpm typecheck

  Finalize:
    needs: [Lint, Types]
    runs-on: ubuntu-latest
    steps:
      - name: Success
        run: echo "All checks passed. Ready to merge!"
  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'RevoTale/eslint-config-nice-nextjs'
    concurrency: release
    # prevents this action from running on forks
    permissions:
      contents: write # to create release (changesets/action)
      pull-requests: write # to create pull request (changesets/action)
      id-token: write

    name: Release
    runs-on: ubuntu-latest
    needs: [Finalize] # Ensure tests pass before running this job
    timeout-minutes: 10 # Added to prevent indefinite runs
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4.1.0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x # Updated to a stable LTS version
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm changeset:version
          publish: pnpm changeset:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}